# Generated by Django 3.1.6 on 2021-02-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portofolio',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
