# Generated by Django 3.1.6 on 2021-02-13 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210211_1139'),
        ('portofolio', '0003_auto_20210211_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='portofolio',
            name='SettingWeb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.setting'),
        ),
    ]
