# Generated by Django 3.1.6 on 2021-02-10 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=200)),
                ('site_descriptions', models.CharField(max_length=255, verbose_name='Descriptions')),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('site_icon', models.ImageField(blank=True, null=True, upload_to='', verbose_name='icon')),
                ('site_social_fb', models.URLField(blank=True, null=True, verbose_name='Facebook Page')),
                ('site_social_twitter', models.URLField(blank=True, null=True, verbose_name='Twitter Page')),
                ('site_social_instagram', models.URLField(blank=True, null=True, verbose_name='Instagram Account')),
            ],
        ),
    ]
