# Generated by Django 3.1.6 on 2021-02-10 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='site_shortdescription',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='site_descriptions',
            field=models.TextField(verbose_name='Descriptions'),
        ),
    ]
