# Generated by Django 3.1.6 on 2021-02-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210210_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='site_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='setting',
            name='site_closetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='site_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='site_opentime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='site_phone',
            field=models.IntegerField(null=True, verbose_name='Phone Number'),
        ),
    ]
