# Generated by Django 3.1.6 on 2021-02-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210211_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='site_closetime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='site_opentime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='site_phone',
            field=models.CharField(max_length=14, null=True, verbose_name='Phone Number'),
        ),
    ]
