# Generated by Django 3.1.6 on 2021-02-11 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Divisi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('div_title', models.CharField(max_length=5, null=True)),
                ('div_descriptions', models.CharField(max_length=100, null=True)),
                ('div_created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='account.divisi'),
        ),
    ]
